import '../../data/enums.dart';
import 'text_cleaner.dart';

class ServiceMatch {
  const ServiceMatch({
    required this.rawText,
    this.service,
    this.confidence = 0,
  });

  /// Exactly what the customer wrote, kept for the "couldn't match" chip.
  final String rawText;

  /// Null when nothing scored high enough. The form is then left empty rather
  /// than filled with a guess.
  final ServiceType? service;
  final double confidence;

  bool get matched => service != null;
}

/// The exact option labels the website offers, in its three languages, plus the
/// app's Vietnamese wording for a request typed by hand. An exact hit here is
/// the common case: the request message is generated by that form.
const Map<ServiceType, List<String>> _canonicalLabels = {
  ServiceType.basicAlterations: [
    'Basic alterations',
    '日常服装修改',
    'Ubah suai asas',
    'Sửa đồ cơ bản',
  ],
  ServiceType.pantsJeansShortening: [
    'Pants / jeans shortening',
    '裤子 / 牛仔裤缩短',
    'Pendekkan seluar / jeans',
    'Cắt lai quần / quần jean',
  ],
  ServiceType.waistSizeAdjustment: [
    'Waist / size adjustment',
    '腰围 / 尺寸调整',
    'Pelarasan pinggang / saiz',
    'Chỉnh eo / kích cỡ',
  ],
  ServiceType.repairZipButton: [
    'Repair / zip / button',
    '修补 / 拉链 / 纽扣',
    'Baiki / zip / butang',
    'Vá / khoá kéo / nút',
  ],
  ServiceType.curtainsBedsheets: [
    'Curtains / bedsheets',
    '窗帘 / 床单',
    'Langsir / cadar',
    'Rèm cửa / ga giường',
  ],
  ServiceType.other: [
    'Other (tell us in notes)',
    '其他（请在备注说明）',
    'Lain-lain (nyatakan di nota)',
    'Khác (ghi rõ trong ghi chú)',
  ],
};

/// Words worth 2 points — on their own they identify the service.
///
/// Vietnamese says `sửa` for both altering and repairing, so it appears in no
/// list on its own: the phrase around it is what picks a side.
const Map<ServiceType, List<String>> _strongKeywords = {
  ServiceType.basicAlterations: [
    'alteration', 'alterations', 'ubah suai', 'ubahsuai', '修改',
    'sửa đồ', 'sua do', 'sửa quần áo', 'sua quan ao',
  ],
  ServiceType.pantsJeansShortening: [
    'shorten', 'shortening', 'hem', 'hemming', 'pendekkan', 'memendekkan', '缩短', '裤脚',
    'lên lai', 'len lai', 'cắt lai', 'cat lai', 'lai quần', 'lai quan', 'cắt ống',
  ],
  ServiceType.waistSizeAdjustment: [
    'waist', 'pinggang', 'taille', '腰围', '尺寸', 'pelarasan',
    'eo', 'nới eo', 'bóp eo', 'chỉnh eo',
  ],
  ServiceType.repairZipButton: [
    'zip', 'zipper', 'button', 'butang', 'repair', 'baiki', '拉链', '纽扣', '修补',
    'khoá kéo', 'khóa kéo', 'khoa keo', 'dây kéo', 'đứt', 'vá', 'sửa khoá',
  ],
  ServiceType.curtainsBedsheets: [
    'curtain', 'curtains', 'bedsheet', 'bedsheets', 'langsir', 'cadar', '窗帘', '床单',
    'rèm', 'rem cua', 'ga giường', 'ga trải giường', 'ga giuong', 'drap',
  ],
  ServiceType.other: [
    'other', 'others', 'lain lain', 'lainlain', '其他', '其它', 'khác', 'khac',
  ],
};

/// Words worth 1 point — supporting evidence only.
const Map<ServiceType, List<String>> _weakKeywords = {
  ServiceType.basicAlterations: [
    'basic', 'asas', 'adjust', 'alter', 'tailor', '日常', '服装',
    'cơ bản', 'co ban', 'chỉnh', 'quần áo',
  ],
  ServiceType.pantsJeansShortening: [
    'pants', 'pant', 'jeans', 'jean', 'trousers', 'trouser', 'seluar', 'slack', 'slacks',
    'length', 'panjang', '裤子', '牛仔裤', '裤',
    'quần', 'quan jean', 'lai', 'ống quần', 'dài',
  ],
  ServiceType.waistSizeAdjustment: [
    'size', 'saiz', 'adjustment', 'adjust', 'loose', 'tight', 'longgar', 'ketat', '调整',
    'kích cỡ', 'kich co', 'cỡ', 'rộng', 'chật',
  ],
  ServiceType.repairZipButton: [
    'fix', 'torn', 'koyak', 'jahit', 'patch', 'hole', '拉鍊', '鈕扣',
    'nút', 'cúc', 'rách', 'thủng',
  ],
  ServiceType.curtainsBedsheets: [
    'sheet', 'sheets', 'duvet', 'blind', 'blinds', 'home', 'rumah', '布帘', '被单',
    'giường', 'màn cửa', 'chăn', 'ga',
  ],
  ServiceType.other: ['misc', 'others', 'dan lain lain', 'dll', 'linh tinh'],
};

/// Enough evidence to fill the field in: one strong keyword, or two weak ones.
const double _confidenceFloor = 2;

/// Maps free text onto [ServiceType], refusing to guess when the evidence is
/// thin. A low-confidence result keeps [ServiceMatch.rawText] so the UI can
/// show it as an unmatched chip.
ServiceMatch matchService(String rawText) {
  final raw = rawText.trim();
  if (raw.isEmpty) return const ServiceMatch(rawText: '');

  final probe = normaliseForMatching(raw);
  if (probe.isEmpty) return ServiceMatch(rawText: raw);

  for (final entry in _canonicalLabels.entries) {
    for (final label in entry.value) {
      if (normaliseForMatching(label) == probe) {
        return ServiceMatch(rawText: raw, service: entry.key, confidence: 1);
      }
    }
  }

  final scores = <ServiceType, double>{};
  for (final type in ServiceType.values) {
    var score = 0.0;
    for (final word in _strongKeywords[type] ?? const <String>[]) {
      if (_containsTerm(probe, word)) score += 2;
    }
    for (final word in _weakKeywords[type] ?? const <String>[]) {
      if (_containsTerm(probe, word)) score += 1;
    }
    scores[type] = score;
  }

  ServiceType? best;
  var bestScore = 0.0;
  var runnerUp = 0.0;
  scores.forEach((type, score) {
    if (score > bestScore) {
      runnerUp = bestScore;
      bestScore = score;
      best = type;
    } else if (score > runnerUp) {
      runnerUp = score;
    }
  });

  // A tie means two services fit equally well — that is exactly the case where
  // guessing does damage, so bail out and let the tailor pick.
  if (best == null || bestScore < _confidenceFloor || bestScore == runnerUp) {
    return ServiceMatch(rawText: raw, confidence: bestScore / 6);
  }

  final margin = (bestScore - runnerUp) / bestScore;
  return ServiceMatch(
    rawText: raw,
    service: best,
    confidence: (0.5 + margin / 2).clamp(0.0, 1.0),
  );
}

/// CJK has no word boundaries, so those terms match as substrings while Latin
/// terms must sit on a word boundary — otherwise "hem" hits "them".
bool _containsTerm(String haystack, String term) {
  if (term.isEmpty) return false;
  if (term.codeUnitAt(0) > 0x2000) return haystack.contains(term);
  final pattern = RegExp(
    '(?<![a-z0-9])${RegExp.escape(term)}(?![a-z0-9])',
    caseSensitive: false,
  );
  return pattern.hasMatch(haystack);
}
